### PR TITLE
Update -> product import detailed report summary.

### PR DESCRIPTION
**Pull request by panshul007**
Print out the formatted JSON object of detailed report summary for product import.

### CODE REVIEW

**Comment by emmenko** [comment]
What's the reason behind this?

**Comment by panshul007** [comment]
@emmenko This is to log out the detailed summary object being returned from the product importer. Currently it logs a very simple message which is not enough information.

**Comment by emmenko** [comment]
Can you show me an example of the problem?

**Comment by panshul007** [comment]
not required anymore

**Pull request closed without merging**
