### PR TITLE
Bump sphere-product-import version

### PR DESCRIPTION
**Pull request by junajan**
#### Summary
Bump version of sphere-product-import module which has support for custom prices references.

### CODE REVIEW

**Comment by hisabimbola** [comment]
@junajan Travis build is currently failing, can you please check it out?

**Comment by Siilwyn** [comment]
*bump*

**Comment by junajan** [comment]
Workin' on It 😁

**Comment by junajan** [comment]
Closing in favor of https://github.com/sphereio/sphere-node-cli/pull/55

**Pull request closed without merging**
