### PR TITLE
chore(orders-update): Bump orders-update module version

### LINKED ISSUE #62: Bumb Orders-update dependency to v2
Title says it all

### PR DESCRIPTION
**Pull request by junajan**
Resolves #62

### CODE REVIEW

**Comment by junajan** [comment]
@wizzy25 `^...` will take the latest minor version - so it should include v2.1.0 too.

**Comment by wizzy25** [comment]
But then, why leave it at 2.0 if you can set it to 2.1?

**Comment by junajan** [comment]
@wizzy25 I was thinking about it but then I realized that if we want to have there the latest version then we should probably wait also for the latest release which is coming out in several hours/days and it would block this PR.. so I decided to put there >=2.0.0 which includes also the latest updates.

But it was just because of some inner feeling... I will try to push a little bit new release of orders-update repo and then change version also here to ^2.2.0.

**Comment by junajan** [comment]
@wizzy25 - updated here 805bfdc

**Pull request merged**
